### ISSUE TITLE
Error: `Action Facade\CodeEditor\Http\Controllers\FileContentsController not defined.`

### ISSUE THREAD

**Issue by mikebronner** [facade/ignition-code-editor#8]
I just installed the package and received this error:
<img width="1073" alt="Screen Shot 2019-09-09 at 12 28 23 PM" src="https://user-images.githubusercontent.com/1791050/64560536-8a475400-d2fd-11e9-929f-57bc4d48c7f0.png">

The underlying exception that triggered this is:
```
[2019-09-09 15:30:31] development.ERROR: Target class [App\Policies\Category] does not exist. (View: /home/vagrant/Sites/ens/resources/views/vendor/nova/layout.blade.php) {"userId":1,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): Target class [App\\Policies\\Category] does not exist. (View: /home/vagrant/Sites/ens/resources/views/vendor/nova/layout.blade.php) at /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Container/Container.php:806, Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [App\\Policies\\Category] does not exist. at /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Container/Container.php:806, ReflectionException(code: -1): Class App\\Policies\\Category does not exist at /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Container/Container.php:804)
[stacktrace]
#0 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Container/Container.php(682): Illuminate\\Container\\Container->build('App\\\\Policies\\\\Ca...')
#1 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Container/Container.php(630): Illuminate\\Container\\Container->resolve('App\\\\Policies\\\\Ca...', Array)
#2 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Illuminate\\Container\\Container->make('App\\\\Policies\\\\Ca...', Array)
#3 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php(624): Illuminate\\Foundation\\Application->make('App\\\\Policies\\\\Ca...')
#4 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php(568): Illuminate\\Auth\\Access\\Gate->resolvePolicy('App\\\\Policies\\\\Ca...')
#5 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(239): Illuminate\\Auth\\Access\\Gate->getPolicyFor('App\\\\Category')
#6 /home/vagrant/Sites/ens/vendor/laravel/nova/src/Authorizable.php(20): Illuminate\\Support\\Facades\\Facade::__callStatic('getPolicyFor', Array)
#7 /home/vagrant/Sites/ens/vendor/laravel/nova/src/Authorizable.php(48): Laravel\\Nova\\Resource::authorizable()
#8 /home/vagrant/Sites/ens/vendor/laravel/nova/src/Nova.php(208): Laravel\\Nova\\Resource::authorizedToViewAny(Object(Illuminate\\Http\\Request))
#9 [internal function]: Laravel\\Nova\\Nova::Laravel\\Nova\\{closure}('App\\\\Nova\\\\Catego...', 13)
#10 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Support/Arr.php(611): array_filter(Array, Object(Closure), 1)
#11 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Support/Collection.php(352): Illuminate\\Support\\Arr::where(Array, Object(Closure))
#12 /home/vagrant/Sites/ens/vendor/laravel/nova/src/Nova.php(210): Illuminate\\Support\\Collection->filter(Object(Closure))
#13 /home/vagrant/Sites/ens/vendor/laravel/nova/src/Nova.php(248): Laravel\\Nova\\Nova::availableResources(Object(Illuminate\\Http\\Request))
#14 /home/vagrant/Sites/ens/vendor/laravel/nova/src/Tools/ResourceManager.php(33): Laravel\\Nova\\Nova::groups(Object(Illuminate\\Http\\Request))
#15 /home/vagrant/Sites/ens/resources/views/vendor/nova/layout.blade.php(40): Laravel\\Nova\\Tools\\ResourceManager->renderNavigation()
#16 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/home/vagrant/S...')
#17 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/home/vagrant/S...', Array)
#18 /home/vagrant/Sites/ens/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate\\View\\Engines\\CompilerEngine->get('/home/vagrant/S...', Array)
#19 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/View/View.php(143): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get('/home/vagrant/S...', Array)
#20 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\\View\\View->getContents()
#21 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#22 /home/vagrant/Sites/ens/vendor/laravel/nova/src/../resources/views/router.blade.php(13): Illuminate\\View\\View->render()
#23 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/home/vagrant/S...')
#24 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/home/vagrant/S...', Array)
#25 /home/vagrant/Sites/ens/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate\\View\\Engines\\CompilerEngine->get('/home/vagrant/S...', Array)
#26 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/View/View.php(143): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get('/home/vagrant/S...', Array)
#27 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\\View\\View->getContents()
#28 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#29 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#30 /home/vagrant/Sites/ens/vendor/symfony/http-foundation/Response.php(202): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#31 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View))
#32 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Routing/Router.php(720): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#33 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#34 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/vagrant/Sites/ens/vendor/laravel/nova/src/Http/Middleware/Authorize.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\\Nova\\Http\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /home/vagrant/Sites/ens/vendor/laravel/nova/src/Http/Middleware/BootTools.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\\Nova\\Http\\Middleware\\BootTools->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home/vagrant/Sites/ens/vendor/laravel/nova/src/Http/Middleware/DispatchServingNovaEvent.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/vagrant/Sites/ens/vendor/laravel/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /home/vagrant/Sites/ens/app/Http/Middleware/EnforceTenancy.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\EnforceTenancy->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /home/vagrant/Sites/ens/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /home/vagrant/Sites/ens/app/Http/Middleware/LoadCurrentOrganization.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\LoadCurrentOrganization->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#64 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#65 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#66 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#67 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#68 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#69 /home/vagrant/Sites/ens/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /home/vagrant/Sites/ens/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /home/vagrant/Sites/ens/vendor/genealabs/laravel-casts/src/Http/Middleware/AssetInjection.php(10): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): GeneaLabs\\LaravelCasts\\Http\\Middleware\\AssetInjection->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /home/vagrant/Sites/ens/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /home/vagrant/Sites/ens/vendor/hyn/multi-tenant/src/Middleware/EagerIdentification.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Hyn\\Tenancy\\Middleware\\EagerIdentification->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /home/vagrant/Sites/ens/vendor/hyn/multi-tenant/src/Middleware/HostnameActions.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Hyn\\Tenancy\\Middleware\\HostnameActions->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#91 /home/vagrant/Sites/ens/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#92 /home/vagrant/Sites/ens/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#93 {main}
"} 
```

**Comment by WilhelmH** [comment]
I got this same error when my APP_ENV was set to `production` and APP_DEBUG set to true. It works when I have `APP_ENV` set to `local`

**Comment by mikebronner** [comment]
My setting is:
```
APP_ENV="development"
```

**Comment by narrative1st** [comment]
Getting this error when deploying to a Staging server through Vapor...(APP_DEBUG set to `true`)

**Comment by axelzuzek** [comment]
Same problem here +1 to @mikebronner s suggestion

**Comment by MatthiasHertel** [comment]
+1

**Comment by jbajou** [comment]
`php artisan cache:clear && php artisan route:clear` and you are good to go (eventually).

**Comment by rvanbaalen** [comment]
Im running into this error when running unit tests.

**Comment by error500** [comment]
I had to `chmod 777 -R storage` to solve this

**Comment by harish444** [comment]
if your are using Centos operationg system 
sudo nano /etc/apache2/apache2.conf  //  ubunto
sudo nano /etc/httpd/conf/httpd.conf

Find the following code inside the editor:

<Directory /var/www/> 
   Options Indexes FollowSymLinks
   AllowOverride None
   Require all granted
</Directory> 

Change to:

<Directory /var/www/> 
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
After that restart the Apache server  or httpd

sudo systemctl restart httpd
or 
sudo systemctl restart apache2

**Comment by jpmc3630** [comment]
I was getting this because I didn't have APP_KEY set in .env.testing
